name: ASCStorage
version: 1.0
main: org.d2d2.ASCStorage.ASCStorage
api-version: 1.16
folia-supported: true
description: A plugin that saves tile entities to an SQLite database.
authors: [GGuPP, Nakars]
