name: ASCStorage
version: 1.0
main: ord.d2d2.ASCStorage.ASCStoragePlugin
api-version: 1.16
description: Плагин для сохранения содержимого шалкеров в базу данных.
commands:
  ascsreload:
    description: Перезагрузка плагина
    permission: ascstorage.admin
permissions:
  ascstorage.admin:
    description: Доступ к административным командам плагина.
    default: op

